package uz.pdp.cinemaroomrestfullservice.entity.enums;

public enum AppPermission {

    //MOVIE RELATED PERMISSION
    VIEW_MOVIES, MANAGE_MOVIE,
    VIEW_ACTORS, MANAGE_ACTOR,
    VIEW_DIRECTORS, MANAGE_DIRECTOR,
    VIEW_DISTRIBUTORS, MANAGE_DISTRIBUTOR,
    VIEW_GENRES, MANAGE_GENRE,

    //MOVIE SESSION RELATED PERMISSIONS
    VIEW_MOVIE_ANNOUNCEMENTS, MANAGE_MOVIE_ANNOUNCEMENT,
    VIEW_MOVIE_SESSIONS, MANAGE_MOVIE_SESSION,
    VIEW_SESSION_DATES, MANAGE_SESSION_DATE,
    VIEW_SESSION_TIMES, MANAGE_SESSION_TIME,

    //CINEMA RELATED PERMISSIONS
    VIEW_HALLS, MANAGE_HALL,
    VIEW_PRICE_CATEGORY, MANAGE_PRICE_CATEGORY,
    VIEW_ROWS, MANAGE_ROW,
    VIEW_SEATS, MANAGE_SEAT,




}
